### ISSUE TITLE
[Bug] Incompat with Dynamic crosshair mod

### ISSUE THREAD

**Issue by DanMeadWasTaken** [CloudG360/Survival-Building-Toolkit#1]
The icon only blinks into existence for a frame when using both this mod and [Dynamic crosshair](https://www.curseforge.com/minecraft/mc-mods/dynamic-crosshair) mod. it's not exactly game breaking immersion- more just a slight annoyance. As the icon basically doesn't show up because it'd seem the Dynamic crosshair mod is overwriting it.

**Comment by squeeglii** [comment]
Was looking into it - It seems a bit out of scope to integrate it into the base mod with all the extra checks needed.

I may make a pull request for the [DynamicCrosshairCompat](https://github.com/Crendgrim/DynamicCrosshairCompat) mod and handle the incompatibility through there.

Will update here with progress.

**Comment by DanMeadWasTaken** [comment]
Thank you <3
