### ISSUE TITLE
Small inconsitancy with block outlines

### ISSUE THREAD

**Issue by nco2k** [CloudG360/Survival-Building-Toolkit#10]
the Bridge-Assist block outlines only show when you are holding a block that you can place, but the **Non**-Bridge-Assist block outlines show regardless of what item you are holding, or even if you are empty handed. it would be cool if you could change it so that both block outlines behaved the same.

**Comment by squeeglii** [comment]
Yeah, that's an oversight. Will fix that up soon 😅

**Comment by squeeglii** [comment]
Fixed in the next release.
