### ISSUE TITLE
[Feature Request] Hold down "SHIFT" to enable "vertical"

### ISSUE THREAD

**Issue by yamakaze-cu** [CloudG360/Survival-Building-Toolkit#14]
I don't know English,Here is the Google translation.

Add a new bridging axis
Hold down "SHIFT" to enable the new bridging axis
![19](https://github.com/squeeglii/BridgingMod/assets/129366484/bd35845b-c67b-43c7-9df4-8b927a1e57a8)

**Comment by squeeglii** [comment]
~~Will add it in the next version! :)~~

Dropping a hotfix first - this will be in 2.4.0

**Comment by yamakaze-cu** [comment]
Thank you very much. Have a wonderful day

**Comment by squeeglii** [comment]
Closing this - added in 2.4.0. Slowly rolling that out for older versions.
