### ISSUE TITLE
[Suggestion] Able to place down variant of the slab and delay

### ISSUE THREAD

**Issue by SLimeyMC** [CloudG360/Survival-Building-Toolkit#2]
if player is half block lower and bridging with slab, it will place down variant ;)
Also add a configurable delay to activate bridging so it doesn't bridge when i don't want to

**Comment by Disketaa** [comment]
+1

**Comment by squeeglii** [comment]
Slab placing is still in the works as I wanted to rewrite the placement logic to make it more feasible. Should see it in a later release.

There's now a way to disable bridging in the config while I work something like a delay. It could also be bindable to a hotkey to give a bit more control perhaps. The new placement logic prioritises vanilla-style placements over bridging anyway which hopefully should make this less of an issue :)

**Comment by squeeglii** [comment]
Right welp, that's both of the features implemented! I've opted for adding a key binding in the end as I think that's a bit more controllable than a delay but feedback is always welcome :)

Shall be shipped in 2.1.0 soonTM
