### ISSUE TITLE
(Probably YACL fault) Cannot edit (2.5.1) config with Better ModList(0.1.10)/Forge config screens(8.0.2) forge 1.20.1/47.3.0

### ISSUE THREAD

**Issue by Xetaxheb** [CloudG360/Survival-Building-Toolkit#24]
![image](https://github.com/user-attachments/assets/13cfbcaa-18e9-49f7-b6ee-b6a080c120ec)
https://modrinth.com/mod/better-modlist

Probably YACL issue? https://github.com/isXander/YetAnotherConfigLib/issues/182

**Comment by squeeglii** [comment]
Try using YACL 3.4.2 if possible. That seems to work.

Versions after that crash for some reason. I've tried to fix it on my end and had no luck. :[
