### ISSUE TITLE
[Bug] Places an extra block when replacing a block

### ISSUE THREAD

**Issue by W2D3F1X2** [CloudG360/Survival-Building-Toolkit#3]
**Description**
When I use left and right buttons in creative mode to replace a block which has another block behind it, an extra block is placed on the clicked surface. 

**Reproduction**
1. Enter creative mode
2. Point to a block which has another block behind it
3. Hold a block
4. Press left and right buttons to replace the pointed block

**Normal behavior**
The held block should be placed in the place of the replaced one, and not placed on its surface.

**Screenshot**
![](https://github.com/CloudG360/BridgingMod/assets/117023186/f4702892-0b8c-4e0f-8a2e-d1406c113fd1)

**Version**
* Minecraft: 1.19.4
* Fabric loader: 0.14.21
* Fabric api: 0.79.0
* BridgingMod: v1.3.0

**Comment by squeeglii** [comment]
It was hard for me to recreate this but I think I managed to do it in the end? 

v2.0.0 should fix this as the placement logic is pretty different. Closing as fixed for now :)
