### ISSUE TITLE
[Suggestion] Block placement preview

### ISSUE THREAD

**Issue by nco2k** [CloudG360/Survival-Building-Toolkit#8]
i really like the "Bridge-assist block outline" feature, and would like to suggest an option to always show a block placement preview, not just when bridging. this way we could use your mod as a general purpose block placement preview mod. it should of course respect the "Only use bridge-assist while crouching" setting.

**Comment by squeeglii** [comment]
I'm a little bit confused by this as vanilla shows an outline when bridging is not being used. Are you suggesting shifting that vanilla outline from the block you can break to the air gap where you can place?

**Comment by nco2k** [comment]
yes.

currently your mod allows us to show an outline when you can bridge:
![pic1](https://github.com/squeeglii/BridgingMod/assets/26080123/d2735730-23e4-46e2-9807-18fd95528706)

im suggesting an option to show that outline whenever you can place a block:
![pic2](https://github.com/squeeglii/BridgingMod/assets/26080123/10c9ea12-53df-4ba3-a8a7-c1cdb4077aaf)

it shouldnt ofc remove the vanilla breaking block outline, but show yours as an addition. this could be incredibly useful at times. especially if you were up for adding another option to show a shape preview like for example when using stairs. this way we can make sure to never accidentally connect them the wrong way. but i think that might go beyond the scope of your mod. one can dream though. :D

**Comment by squeeglii** [comment]
Ahh awesome. Adding that shouldn't be too bad then. Will consider fancy outlines for a later update but a simple box will do for now.

Should be in the next update! :]

**Comment by squeeglii** [comment]
Implemented with a few config options - it's off by default but the you can find the setting in the "Visual" category.

Will be in v2.3.0. Thanks for the suggestion!

**Comment by nco2k** [comment]
wow that was fast. thanks for adding this!

there is one small cosmetic issue though. the bridging outline color (white) merges with the vanilla outline color (black) and therefor creates a new in-between color (grey) when the two outlines overlap. any chance you can fix that?

![outline1](https://github.com/squeeglii/BridgingMod/assets/26080123/11d986c9-1429-434d-988c-5992b5171886)
![outline2](https://github.com/squeeglii/BridgingMod/assets/26080123/c4b719d0-c12a-42c6-a661-86993557e453)

**Comment by squeeglii** [comment]
Have you set the lines to full opacity? The colour `#ffffffff` should do that. Transparency will lead to blending and there's not an easy way to fix that without modifying the vanilla outline.

**Comment by nco2k** [comment]
yes im using `#ffffffff`

**Comment by squeeglii** [comment]
Strange - it didn't look the same on my end. Are you using any mods that modify your graphics?
I've tried it on Fast, Fancy, & Fabulous on Fabric.

**Comment by nco2k** [comment]
okay it looks like its caused by Iris Shaders, even if no shader pack is currently being used.

i could reproduce it with just the following mods:

- Fabric API 0.96.11+1.20.4
- Sodium 1.20.4-0.5.8
- Iris Shaders 1.6.17+1.20.4
- Cloth Config API 13.0.121
- Bridging Mod 2.3.0+1.20.4

as soon as i remove Iris Shaders, it works as intended. very strange.

**Comment by squeeglii** [comment]
fuuuun, I love vague and mysterious graphical bugs. 💀

Will move this into a new issue. Not sure how long it'll take to fix as it's quite minor and doesn't have a clear cause, but I'll take a look either way.
